trigger:
- main

pool:
  name: 'Default'  # your self-hosted agent pool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Found project file: %%f
      dotnet restore "%%f"
      EXIT /B 0
    )
  displayName: 'Restore packages'
  workingDirectory: '$(Build.SourcesDirectory)'

- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Building: %%f
      dotnet build "%%f" --configuration Release
      EXIT /B 0
    )
  displayName: 'Build'
  workingDirectory: '$(Build.SourcesDirectory)'

- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Publishing: %%f
      dotnet publish "%%f" -c Release -o $(Build.ArtifactStagingDirectory)
      EXIT /B 0
    )
  displayName: 'Publish'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
