trigger:
- main

pool:
  name: 'Default'  # Self-hosted agent name

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore juan_quiz4.csproj
    dotnet build juan_quiz4.csproj --configuration Release
    dotnet publish juan_quiz4.csproj -c Release -o $(Build.ArtifactStagingDirectory)/published
  displayName: 'Restore, Build & Publish'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/published'
    ArtifactName: 'drop'
    publishLocation: 'Container'
