trigger:
- main

pool:
  name: 'Default'  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408' 
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore
  workingDirectory: '.'
  displayName: 'Restore packages'

- script: dotnet build --configuration Release
  workingDirectory: '.'
  displayName: 'Build'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  workingDirectory: '.'
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
