trigger:
- main

pool:
  name: 'Default'  # 

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    for /r %%f in (*.csproj) do (
      echo %%f > projectpath.txt
      goto done
    )
    :done
    set /p projpath=<projectpath.txt
    echo Found project: %projpath%
    call dotnet restore "%projpath%"
    call dotnet build "%projpath%" --configuration Release
    call dotnet publish "%projpath%" -c Release -o "$(Build.ArtifactStagingDirectory)\published"
  displayName: 'Restore, Build & Publish'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/published'
    ArtifactName: 'drop'
    publishLocation: 'Container'
