trigger:
- main

pool:
  name: 'Default'  
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    for /r %%f in (*.csproj) do (
      echo Using project file: %%f
      set "projectPath=%%f"
      goto done
    )
    :done
    echo Restoring %%projectPath%%
    call dotnet restore "%%projectPath%%"
    call dotnet build "%%projectPath%%" --configuration Release
    call dotnet publish "%%projectPath%%" -c Release -o "$(Build.ArtifactStagingDirectory)\published"
  displayName: 'Restore, Build & Publish'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/published'
    ArtifactName: 'drop'
    publishLocation: 'Container'
