trigger:
- main

pool:
  name: 'Default'  

variables:
  solutionPath: '$(Build.SourcesDirectory)/juan_quiz4.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore "$(solutionPath)"
  displayName: 'Restore packages'

- script: dotnet build "$(solutionPath)" --configuration Release
  displayName: 'Build'

- script: dotnet publish "$(solutionPath)" -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
