trigger:
- main

pool:
  name: 'Default'  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.408'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore Step
- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Restoring: %%f
      dotnet restore "%%f"
      EXIT /B 0
    )
  displayName: 'Restore packages'
  workingDirectory: '$(Build.SourcesDirectory)'

# Build Step
- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Building: %%f
      dotnet build "%%f" --configuration Release
      EXIT /B 0
    )
  displayName: 'Build'
  workingDirectory: '$(Build.SourcesDirectory)'

# Publish Step
- script: |
    FOR /R %%f IN (*.csproj) DO (
      ECHO Publishing: %%f
      dotnet publish "%%f" -c Release -o "$(Build.ArtifactStagingDirectory)/published"
      EXIT /B 0
    )
  displayName: 'Publish'
  workingDirectory: '$(Build.SourcesDirectory)'

# Upload Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/published'
    ArtifactName: 'drop'
    publishLocation: 'Container'
